### ISSUE TITLE
Error on trying to execute SqlTZLoader.exe

### ISSUE THREAD

**Issue by AashishJha** [mj1856/SqlServerTimeZoneSupport#10]
![capture](https://cloud.githubusercontent.com/assets/16673886/13147120/f9cd82d2-d625-11e5-8c08-ab13779a58cc.PNG)

**Comment by mattjohnsonpint** [comment]
The app is a simple .net console utility.  It shouldn't invoke visual studio.  Anyway, that error is unrelated.  See:  http://stackoverflow.com/questions/2673275/how-do-i-fix-an-invalid-license-data-reinstall-is-required-error-in-visual-c
