### ISSUE TITLE
tzdb.sql Missing

### ISSUE THREAD

**Issue by stevenmcneese** [mj1856/SqlServerTimeZoneSupport#11]
Step 3 calls for executing tzdb.sql against my database but I cannot find it in the downloaded package.  Is the readme out of date?  My database is v 2014 hosted by a cloud provider.  I have access to the database via SSMS 2016.

**Comment by mattjohnsonpint** [comment]
Sorry for the delayed response.

The compiled tzdb.sql is included in the `sqltz.zip` file on the [releases page](https://github.com/mj1856/SqlServerTimeZoneSupport/releases).

The sources that build the file are in the [/Database](https://github.com/mj1856/SqlServerTimeZoneSupport/tree/master/Database) folder.
