### ISSUE TITLE
Support parameters to the SqlTzLoader

### ISSUE THREAD

**Issue by mattjohnsonpint** [mj1856/SqlServerTimeZoneSupport#2]
- We currently populate the Intervals table for 5 years in the future.
- The connection string is pulled from the config file.

Both of these should be things that can be passed in on the command line arguments.

**Comment by darshanrampatel** [comment]
One thing I would like is to be able to specify a list of TimeZones that I want to load in from the NodaTime DB - would this be possible? (Sorry, not familiar at all with NodaTime!)

I suppose this could be done by editing the loop in the exe around [here](https://github.com/mj1856/SqlServerTimeZoneSupport/blob/master/SqlTzLoader/Program.cs#L46) to check for a zone is a specified list?

**Comment by mattjohnsonpint** [comment]
I'd probably do that slightly earlier, [around here](https://github.com/mj1856/SqlServerTimeZoneSupport/blob/3f6e6d6247be7b9a737721d6c197fbcd5f2c3c14/SqlTzLoader/Program.cs#L23).  `tzdb.Ids` contains all identifiers from the loaded tzdb provider.  One would just filter this list, then call `WriteZonesAsync` on the filtered list instead of the entire list.

I can see a couple of command-line options would be needed to do that effectively.  One to include _only_ a few time zones, another to include all time zones _except_ a few, and another to include time zones provided in an external file, when a large list of zones would be too awkward to put on the command line.

**Comment by darshanrampatel** [comment]
Great! Thanks for the advice - will give this a go myself in the .CS for now.

**Comment by mattjohnsonpint** [comment]
Sure! Feel free to send a PR on this if you like.

**Comment by rykerwilliams** [comment]
Hi, I'm looking at addressing this issue, for use of SqlTzLoader in one of my projects. I wanted to use: https://commandline.codeplex.com/license

as it is available as a nuget package. Comments or thoughts? I will likely use some library to handle the arguments, rather than rolling my own. 

I'm most interested in adding connectionstring as an argument. Thanks!

**Comment by mattjohnsonpint** [comment]
Sure!  A PR would be welcomed.  Thanks!

**Comment by mattjohnsonpint** [comment]
Closed with #8
