### ISSUE TITLE
Question/Suggestion - Connecting to Countries

### ISSUE THREAD

**Issue by jetfueldev** [mj1856/SqlServerTimeZoneSupport#25]
This is an observation/question. Maybe I'm missing something. I love the ease of use of this on importing everything related to time zones. Has there been any thought on connecting these in some way with a mapping table or so forth to the actual countries via ISO country codes?

**Comment by david-c14** [comment]
What sort of link would you be wanting? 

An ISO country code might refer to a country with multiple time zones.

**Comment by martincheck** [comment]
It looks like this has been covered in moment.  I wonder if the logic could be re-used for this application:
 https://github.com/moment/moment-timezone/issues/289

**Comment by toviszsolt** [comment]
**The question is not silly at all, I also need a solution.**

- In such cases, the expected operation is that if there are multiple matches, an array is returned with all matching values.
- The developer then decides which element of the array to use. In most cases, probably the first element, but one has to think of more complex uses, so it would be perfect if all time zones could be obtained in one array.
- In addition, the array should somehow return in a form that allows further operations to be performed.

Thank you.
