### ISSUE TITLE
Is Tzdb.Intervals Missing YEKT? (Yekaterinburg Time)

### ISSUE THREAD

**Issue by robarwebservices** [mj1856/SqlServerTimeZoneSupport#29]
It seems that the Tzdb.Intervals table is missing the YEKT entry. 

[https://en.wikipedia.org/wiki/Yekaterinburg_Time](https://en.wikipedia.org/wiki/Yekaterinburg_Time)

I checked the [List of tz database time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) on wikipedia and Yekaterinburg does exists in the list there.

**Comment by mattjohnsonpint** [comment]
All data is imported from the tzdb via NodaTime.  `Asia/Yekaterinburg` is indeed a valid identifier.

Perhaps you are referring to the abbreviation `YEKT` itself?  The tzdb has been removing many "invented" abbreviations.  That one was dropped in 2016g. [See announcement](https://mm.icann.org/pipermail/tz-announce/2016-September/000041.html).
