### ISSUE TITLE
The timezone provided to builtin function todatetimeoffset is invalid

### ISSUE THREAD

**Issue by mikegong** [mj1856/SqlServerTimeZoneSupport#3]
Got above error when using function Tzdb.UtcToLocal. This issue was caused by a bug of TODATETIMEOFFSET of SQL Server, https://social.msdn.microsoft.com/Forums/sqlserver/en-US/6c38a5cd-8b18-40b6-a5cb-56c45abdc2fd/todatetimeoffset-fails-only-when-reading-smallint-offset-value-out-of-a-table?forum=transactsql.

This problem can be resolved by changing OffsetMinutes from smallint to int.

**Comment by mattjohnsonpint** [comment]
Very interesting!  May I ask what version (and service pack) of SQL Server you are using?

**Comment by mikegong** [comment]
I tested it on SQL Server 2008 R2 RTM. 

BTW, I did not change the data type of OffsetMinites in tables, just changed Declare in function.
